FROM openjdk:8
WORKDIR /noteapp/bin
ENV PORT 90
COPY /target/classes /noteapp/bin/classes
COPY /target/dependency /noteapp/bin/dependency
CMD ["java","-cp","./classes:./dependency/*","com.appserver.App"]